# frozen_string_literal: true

source 'https://rubygems.org'

gem 'daemons'
gem 'dotenv'
gem 'grpc'
gem 'google-protobuf'
gem 'mongoid', '~> 7.0'
gem 'logging'
gem 'pry'
gem 'rake'
gem 'rspec'
gem 'timecop'