# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discounts/discount.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "discounts.Discount" do
    optional :pct, :float, 1
    optional :value_in_cents, :int32, 2
  end
  add_message "discounts.DiscountRequest" do
    optional :user_id, :string, 1
    optional :product_id, :string, 2
  end
  add_message "discounts.DiscountResponse" do
    optional :discount, :message, 1, "discounts.Discount"
  end
end

module Discounts
  Discount = Google::Protobuf::DescriptorPool.generated_pool.lookup("discounts.Discount").msgclass
  DiscountRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("discounts.DiscountRequest").msgclass
  DiscountResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("discounts.DiscountResponse").msgclass
end
