# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users/user.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "users.User" do
    optional :id, :string, 1
    optional :first_name, :string, 2
    optional :last_name, :string, 3
    optional :date_of_birth, :message, 4, "google.protobuf.Timestamp"
  end
end

module Users
  User = Google::Protobuf::DescriptorPool.generated_pool.lookup("users.User").msgclass
end
